name: CI

on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.os }}-node-

      - name: Testing
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
          cd client
          npm ci
          npm run test

      - name: Build Project
        if: github.event_name == 'push'
        run: cd client && npm run build:dev

      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: cd client && npx surge --project ./dist/client --domain staging-shreyasssk.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
