name: Notify on Issue
on:
  issues:
    types: [opened]

jobs:
  issue-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Open Issue
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'New Issue Created! :no_entry:'
          SLACK_MESSAGE: 'New Issue created! <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}.> '
          MSG_MINIMAL: event,commit
