name: Notify on Release
on:
  release:
    types: [published]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack slack-message
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: github-bot
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'New Release Created! :package: :tada: :confetti_ball:'
