name: Notify on Release
on:
  release:
    types: [published]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Release Created
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'New Release Created! :package: :tada: :confetti_ball:'
          SLACK_MESSAGE: '<${{ github.event.release.html_url }}|check it out now.>'
          MSG_MINIMAL: event,commit
